sudo: required
services:
  - docker

before_install:
  - docker build -t tonytang0114/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tonytang0114/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerwithreact"
  env: "Dockerwithreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-198771294253"
  bucket_path: "dockerwithreact"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
